services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esperanca-worker
    environment:
      DOTNET_ENVIRONMENT: Development

      ConnectionStrings__MongoDb: "mongodb://host.docker.internal:27017"
      Mongo__DatabaseName: "doacoes_db"
      Mongo__DoacoesCollection: "doacoes"
      Mongo__PainelMacroCollection: "painel_macro"
      Mongo__ListaCampanhasCollection: "lista_campanhas"
      Mongo__CampanhaDetalheCollection: "campanha_detalhe"

      RabbitMq__Host: "host.docker.internal"
      RabbitMq__Port: "5672"
      RabbitMq__User: "guest"
      RabbitMq__Password: "guest"
      RabbitMq__VirtualHost: "/"
      RabbitMq__Exchange: "esperanca.doacoes"
      RabbitMq__DeadLetterExchange: "esperanca.doacoes.dlx"

      RabbitMq__RecebidaQueue: "doacoes-recebidas"
      RabbitMq__RecebidaRoutingKey: "recebida"
      RabbitMq__RecebidaDeadLetterQueue: "doacoes-recebidas-dlq"

      RabbitMq__PrefetchCount: "1"
    restart: unless-stopped
