apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: esperanca
spec:
  replicas: 1
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker }
    spec:
      containers:
        - name: worker
          image: fzndev/fiap-ong-esperanca-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef: { name: worker-config }
          env:
            - name: RabbitMq__User
              valueFrom: { secretKeyRef: { name: esperanca-secrets, key: RABBITMQ_USER } }
            - name: RabbitMq__Password
              valueFrom: { secretKeyRef: { name: esperanca-secrets, key: RABBITMQ_PASSWORD } }